#!/bin/sh

# KEYWORD: firstboot
# PROVIDE: cs_configinit
# REQUIRE: NETWORKING
# BEFORE: SERVERS cs_fetchkey firstboot_freebsd_update firstboot_pkgs

# Define cs_configinit_enable=YES in /etc/rc.conf to enable automatic
# system configuration from cloudstack user-data when the system first boots.
: ${cs_configinit_enable=NO}

. /etc/rc.subr

name="cs_configinit"
rcvar=cs_configinit_enable
start_cmd="cs_configinit_run"
stop_cmd=":"

CONFIGURL="http://169.254.169.254/latest/user-data"

cs_configinit_run()
{
	# Download to a temporary location.
	echo -n "Fetching cloudstack user-data"
	CONFFILE=`mktemp "${TMPDIR:-/tmp}/configinit.XXXXXX"`
	fetch -o ${CONFFILE} ${CONFIGURL} 2>/dev/null

	# If we succeeded, process it; otherwise report failure.
	if [ $? = 0 ]; then
		# Process the user-data.
		echo .
		echo -n "Processing cloudstack user-data"
		/usr/local/sbin/cs_configinit $CONFFILE
		echo .
	else
		echo " failed."
	fi

	# Whether we suceeded or not, delete the temporary file.
	rm $CONFFILE

	# Signal /etc/rc to reload rc.conf in case it changed.
	kill -ALRM $$
}

load_rc_config $name
run_rc_command "$1"
